Add fireball to boss
PaGr0m/RogueLike pull request #118
Opened 2020-06-07 20:07 UTC by HarmlessEvil

2020-06-08 16:11 UTC, ZhekehZ requested changes

2020-06-08 16:11 UTC, ZhekehZ commented on src/main/java/ru/itmo/roguelike/characters/Player.java
> +    public Player(@NotNull EventManager eventManager) {
Мб `bossManager` тоже зиаинжектить?

2020-06-08 16:11 UTC, ZhekehZ commented on src/main/java/ru/itmo/roguelike/characters/Player.java
> +                });
```suggestion
            bossManager.createBoss();
```
Это, вроде, то же самое

2020-06-08 16:11 UTC, ZhekehZ commented on src/main/java/ru/itmo/roguelike/characters/mobs/PersonX.java
> +            if (lineOfSight.getX() <= 32 || lineOfSight.getY() <= 32) {
только 4 направления?

2020-06-08 16:11 UTC, ZhekehZ commented on src/main/java/ru/itmo/roguelike/manager/actormanager/BossManager.java
> +public class BossManager {
`@Singleton`

2020-06-08 16:11 UTC, ZhekehZ commented on src/main/java/ru/itmo/roguelike/manager/actormanager/BossManager.java
> +        this.gameManager = gameManager;
если инжектить, то вместо этого setter

2020-06-08 16:11 UTC, ZhekehZ commented on src/main/java/ru/itmo/roguelike/manager/actormanager/BossManager.java
> +                for (IntCoordinate coordinate : new IntCoordinate[]{
Этот цикл проверяет каждую 100ю клетку (одну клетку), так и задумывалось?

2020-06-08 16:11 UTC, ZhekehZ commented on src/main/java/ru/itmo/roguelike/manager/gamemanager/GameManager.java
> +        bossManager = new BossManager(this);
если инжектить, что тут setter

2020-06-08 18:23 UTC, HarmlessEvil commented on src/main/java/ru/itmo/roguelike/characters/Player.java
> +    public Player(@NotNull EventManager eventManager) {
Циклическая зависимость на `GameManager`(

2020-06-08 18:23 UTC, HarmlessEvil commented on src/main/java/ru/itmo/roguelike/characters/Player.java
> +                });
🤦

2020-06-08 18:24 UTC, HarmlessEvil commented on src/main/java/ru/itmo/roguelike/characters/mobs/PersonX.java
> +            if (lineOfSight.getX() <= 32 || lineOfSight.getY() <= 32) {
Это в принципе особо нежизнеспособно, пока direction не во `FloatCoordinate`

2020-06-08 18:24 UTC, HarmlessEvil commented on src/main/java/ru/itmo/roguelike/manager/actormanager/BossManager.java
> +public class BossManager {
Нет смысла так помечать классы, которые не входят в граф зависимостей

2020-06-08 18:25 UTC, HarmlessEvil commented on src/main/java/ru/itmo/roguelike/manager/actormanager/BossManager.java
> +                for (IntCoordinate coordinate : new IntCoordinate[]{
Я копировал твой код)) Не

2020-06-09 16:16 UTC, ZhekehZ approved these changes

2020-06-09 16:18 UTC, merged