Create Decorator for Mover
PaGr0m/RogueLike pull request #14
Opened 2020-05-20 23:10 UTC by PaGr0m

2020-05-20 23:23 UTC, ZhekehZ commented
(тест ревью)

2020-05-20 23:24 UTC, ZhekehZ requested changes

2020-05-20 23:24 UTC, ZhekehZ commented on src/main/java/ru/itmo/roguelike/characters/movement/MoverEmbarrassment.java
> +    private final Map<MoveTo, Integer> moveMap = new EnumMap<>(MoveTo.class);
не static?

2020-05-20 23:24 UTC, ZhekehZ commented on src/main/java/ru/itmo/roguelike/characters/movement/MoverEmbarrassment.java
> +        return super.getWrapped();
тут нужно передать effect и результат завернуть в текущий эффект

2020-05-20 23:26 UTC, PaGr0m commented on src/main/java/ru/itmo/roguelike/characters/movement/MoverEmbarrassment.java
> +    private final Map<MoveTo, Integer> moveMap = new EnumMap<>(MoveTo.class);
Думал про `static`, но потом подумал, а зачем? Все равно только он же использует его. Чтобы он строился сразу при загрузке класса?

2020-05-20 23:27 UTC, PaGr0m commented on src/main/java/ru/itmo/roguelike/characters/movement/MoverEmbarrassment.java
> +        return super.getWrapped();
Там сейчас проблема, что `wrapper` является `null'ом`. Мб потому, что вызывается просто `new` активации. Завтра уже гляну.

2020-05-20 23:28 UTC, ZhekehZ commented on src/main/java/ru/itmo/roguelike/characters/movement/MoverEmbarrassment.java
> +    private final Map<MoveTo, Integer> moveMap = new EnumMap<>(MoveTo.class);
чтобы он не создавался при каждом инстанциировании класса

2020-05-20 23:32 UTC, ZhekehZ requested changes

2020-05-20 23:32 UTC, ZhekehZ commented on src/main/java/ru/itmo/roguelike/characters/Player.java
> +    private Mover mover;
нет инициализации

2020-05-20 23:32 UTC, ZhekehZ commented on src/main/java/ru/itmo/roguelike/characters/movement/MoverEmbarrassment.java
> +        return super.getWrapped();
да, но это другая проблема

2020-05-21 10:19 UTC, ZhekehZ requested changes

2020-05-21 10:19 UTC, ZhekehZ commented on src/main/java/ru/itmo/roguelike/characters/movement/MoverEmbarrassment.java
> +        return super.getWrapped(effect);
так теряются все эффекты выше текущего. нужно либо создать новый инстанс, либо изменить текущий:
```
wrapped = super.getWrapped(effect);
return this;
```

2020-05-21 18:12 UTC, ZhekehZ approved these changes

2020-05-21 18:14 UTC, merged