Release game №1 (to check)
PaGr0m/RogueLike pull request #22
Opened 2020-05-23 22:06 UTC by PaGr0m

**Для первой итерации требовалось:**
- [x] Консольная графика 
- [x] Персонаж, перемещающийся по карте
- [x] Карта должна на выбор пользователя случайно генерироваться или грузиться из файла
- [x] Специальных требований на генератор карт не накладывается, но красивые результаты приветствуются

На данный момент карта генерируется псевдослучайно и по ней бегает может бегать персонаж. Добавлена коллизия с некоторыми объектами.

---

**Для второй итерации требовалось:**
- [x] Несколько разных видов, различающихся характеристиками и поведением (паттерн "Стратегия"):
  - Агрессивное поведение, атакуют игрока, как только его видят
  - Пассивное поведение, просто стоят на месте
  - Трусливое поведение, стараются держаться на расстоянии от игрока
- [ ] При попытке занять одну клетку существа атакуют друг друга (но не занимают клетку, пока одно из существ не уничтожено)
- [x] Используя паттерн "Декоратор", реализовать заклинание конфузии, накладываемое на игрока. Игрок, находящийся под эффектом конфузии, перемещается, случайно выбирая направление из трёх, наиболее близких к направлению, выбранному игроком (например, при попытке сделать шаг вверх игрок с равной вероятностью делает шаг вверх, вверх-влево или вверх-вправо). Эффект должен быть временным.

В данном **PR** поведения через стратегию заданы, но мобы добавлены вручную (допиливается). Заклинание "Конфузия" выполнена через шаблон "Декоратор", но в игру еще не добавлено то, что активирует его.

2020-05-25 15:26 UTC, ottergottaott requested changes
Работа хорошая.

Не нашел как поддержана загрузка карты из файла вместо случайной генерации. И не увидел этого в игре, если все-таки поддержана. 

Ниже оставил немного комментареив и вопросов.

Также придется дописать побольше тестов, не только к `NoiseGenerator`,  а также покрыть код комментариями.

2020-05-25 15:26 UTC, ottergottaott commented on src/main/java/ru/itmo/roguelike/characters/mobs/strategy/CowardlyBehavior.java
> +    }
Дублирование с `AggressiveBehavior`

2020-05-25 15:26 UTC, aleksZubakov commented on src/main/java/ru/itmo/roguelike/characters/mobs/strategy/MobWithTarget.java
> +public interface MobWithTarget extends MobBehavior, WithTarget {
Можно в `WithTarget` добавить метод `getTarget`, в `MobBehavior` -- `getSelf`. Тогда в этом интерфейсе получится сделать дефолтную реализацию и дублирование уйдет.

Еще обратите внимание, что `AggressiveBehavior` и `CowardlyBehavior` не отличаются совсем, есть ли смысл делать два класса?

2020-05-25 15:26 UTC, aleksZubakov commented on src/main/java/ru/itmo/roguelike/characters/mobs/strategy/CowardlyBehavior.java
> +    public Pair<Integer, Integer> getPath() {
Разве не с `Coordinate` тут должны работать?

2020-05-25 15:26 UTC, aleksZubakov commented on src/main/java/ru/itmo/roguelike/characters/mobs/strategy/CowardlyBehavior.java
> +            return new Pair<>(0, 0);
Выражать невозможность нахождения пути через пару с нулями не очень хорошая идея. Лучше подчеркнуть, что валидный результат не всегда можно получить и возвращать `Optional`

2020-05-25 15:26 UTC, aleksZubakov commented on src/main/java/ru/itmo/roguelike/items/Collectible.java
> +    int bonusSize;
Неиспользованные package-private переменные

2020-05-25 15:26 UTC, aleksZubakov commented on src/main/java/ru/itmo/roguelike/items/Collectible.java
> +    int bonusSize;
У наследников такая же история

2020-05-25 15:26 UTC, aleksZubakov commented on src/main/java/ru/itmo/roguelike/manager/gamemanager/GameManager.java
> +        // Effects
Не должно быть закомментированного кода

2020-05-25 15:26 UTC, aleksZubakov commented on src/main/java/ru/itmo/roguelike/map/NoiseGenerator.java
> +        return Math.abs(1.0f - ((v * (v * v * 15731 + 789221) + 1376312589) & 0x7fffffff) / 1073741824.0f);
0_0

2020-05-25 15:26 UTC, aleksZubakov commented on src/main/java/ru/itmo/roguelike/map/NoiseGenerator.java
> +     * Generates ValueNoise {@see "https://habr.com/ru/post/142592/"}
Лучше это к самому классу написать, чтобы читающий сразу мог понять что тут будет происходить

2020-05-25 15:26 UTC, aleksZubakov commented on src/main/java/ru/itmo/roguelike/map/Chunk.java
> +    // Single thread only!
Такие комментарии тоже, конечно, лучше к классу писать

2020-05-25 15:26 UTC, aleksZubakov commented on src/main/java/ru/itmo/roguelike/manager/actormanager/ProjectileManager.java
> +    private final static List<Projectile> registry = new ArrayList<>();
Напомню, что в java поддерживает такое достижение человечества, как  generics.

Обратите внимание, что `ProjectileManager` и `MobManager` отличаются только типом сущностей, которыми они оперируют, все остальное повторяется

2020-05-25 15:26 UTC, aleksZubakov commented on src/main/java/ru/itmo/roguelike/Application.java
> +        timer.schedule(renderScheduler, 0, 1000 / GameSettings.FPS);
А что будет, если один шаг `renderScheduler` займет больше, чем `1000 / GameSettings.FPS`?

2020-05-26 15:39 UTC, HarmlessEvil commented on src/main/java/ru/itmo/roguelike/characters/mobs/strategy/CowardlyBehavior.java
> +            return new Pair<>(0, 0);
Здесь мы хотим идейно подчеркнуть не что "Не получилось найти путь", а что "Actor должен стоять на месте"

2020-05-26 16:34 UTC, karl-crl commented on src/main/java/ru/itmo/roguelike/map/NoiseGenerator.java
> +     * Generates ValueNoise {@see "https://habr.com/ru/post/142592/"}
Поправили

2020-05-26 16:35 UTC, karl-crl commented on src/main/java/ru/itmo/roguelike/map/Chunk.java
> +    // Single thread only!
Поправили

2020-05-28 20:15 UTC, aleksZubakov commented on src/main/java/ru/itmo/roguelike/characters/mobs/strategy/CowardlyBehavior.java
> +            return new Pair<>(0, 0);
Это как раз хорошо и выражается через `Optional.empty`. По объекту с какими-то значениями (пусть и интуитивными, т.к. 0) сложнее сказать, что "Actor должен стоять на месте", это все-таки "Actor должен отойти на расстояние 0, 0", что близко, но не тоже самое

Но ок, не буду настаивать

2020-06-04 19:15 UTC, merged